#!/bin/sh
arm-linux-gnueabihf-objcopy -O binary -R .note -R .comment -R .ARM.attributes -S -j .text linux-system.axf .text
arm-linux-gnueabihf-objcopy -O binary -R .note -R .comment -R .ARM.attributes -S -j .monitor linux-system.axf .monitor
